# Generated by Django 4.2.6 on 2025-02-12 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderitemmodel',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.ordermodel'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='clients.addressmodel'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='clients.clientmodel'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
