# Generated by Django 4.2.6 on 2025-02-12 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_addressmodel_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressmodel',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
