# Generated by Django 4.2.6 on 2025-02-13 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_addressmodel_postal_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addressmodel',
            name='postal_code',
        ),
    ]
